mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from papers import views as papers_views

urlpatterns = [
    path('', include('papers.urls', namespace='papers')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', papers_views.register, name='register'),
    path('accounts/<int:pk>/', papers_views.UserDetailView.as_view(), name='user-detail'),
    path('accounts/<int:pk>/edit', papers_views.user_update, name='user-update'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('rosetta/', include('rosetta.urls')),
    ] + urlpatterns

papers/urls.py
from django.urls import path

from papers import views

app_name = 'papers'
urlpatterns = [
    path('', views.PaperListView.as_view(), name='paper-list'),
    path('paper/<int:pk>/', views.PaperDetailView.as_view(), name='paper-detail'),
    path('paper/<int:pk>/edit', views.paper_update, name='paper-update'),
    path('paper/<int:pk>/download', views.paper_download, name='paper-download'),
    path('paper/<int:pk>/delete', views.PaperDeleteView.as_view(), name='paper-delete'),
    path('paper/new', views.paper_create, name='paper-create'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
]

papers/models.py
from functools import partial

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _, pgettext_lazy

from taggit.managers import TaggableManager

from papers.validators import file_size, file_type


class Author(models.Model):
    user = models.OneToOneField(User, verbose_name=_('user'), on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=150)
    email_address = models.EmailField(_('email address'), blank=True)
    affiliation = models.CharField(_('affiliation'), max_length=128)
    postal_address = models.CharField(_('postal address'), max_length=128, blank=True)
    phone_number = models.CharField(_('phone number'), max_length=32, blank=True)

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('papers:author-detail', args=[str(self.id)])


@receiver(post_save, sender=User)
def update_author(sender, instance, created, **kwargs):
    if created:
        Author.objects.create(user=instance)
    instance.author.save()


class Paper(models.Model):
    title = models.CharField(pgettext_lazy("Paper's title", 'title'), max_length=255)
    abstract = models.TextField(pgettext_lazy("Paper's abstract", 'abstract'))
    keywords = TaggableManager(verbose_name=_('keywords'), blank=True)
    authors = models.ManyToManyField(
        Author,
        verbose_name=_('authors')
    )
    file = models.FileField(_('file'),
                            validators=[partial(file_size, settings.MAX_FILE_SIZE),
                                        partial(file_type, settings.ALLOWED_MIME_TYPES)],
                            help_text=_('Maximum size: %(size)s MiB. Filetypes: %(filetypes)s.' % {
                                'size': settings.MAX_FILE_SIZE,
                                'filetypes': ", ".join(settings.ALLOWED_FILE_EXTENSIONS)}))
    filename = models.CharField(_('filename'), max_length=255)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=pgettext_lazy('Paper was created by', 'created by'),
    )
    created_at = models.DateTimeField(pgettext_lazy("paper's creation time", 'created at'), auto_now_add=True)
    modified_at = models.DateTimeField(pgettext_lazy("paper's modification time", 'modified at'), auto_now=True)

    class Meta:
        verbose_name = _('paper')
        verbose_name_plural = _('papers')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('papers:paper-detail', args=[str(self.id)])

papers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from papers.models import Author, Paper
from django.utils.translation import gettext_lazy as _


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name',
                  'last_name',
                  'email_address',
                  'affiliation',
                  'postal_address',
                  'phone_number']


class PaperForm(ModelForm):
    class Meta:
        model = Paper
        fields = ['title',
                  'abstract',
                  'keywords',
                  'file']


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label=_('email address'),
                             help_text=_('This can be used to reset your password.'),
                             required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class UserUpdateForm(ModelForm):
    email = forms.EmailField(label=_('email address'),
                             help_text=_('This can be used to reset your password.'),
                             required=True)

    class Meta:
        model = User
        fields = ('email',)

    def save(self, commit=True):
        user = super(UserUpdateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

papers/views.py
import magic
from urllib.parse import quote_plus

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView

from rules.contrib.views import permission_required, objectgetter, PermissionRequiredMixin

from papers.forms import AuthorForm, PaperForm, RegisterForm, UserUpdateForm
from papers.models import Author, Paper


class SimpleDetailView(DetailView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fields'] = self.fields
        return context


class PaperDetailView(PermissionRequiredMixin, DetailView):
    model = Paper
    permission_required = 'papers.access_paper'


class PaperDeleteView(PermissionRequiredMixin, DeleteView):
    model = Paper
    permission_required = 'papers.access_paper'
    success_url = reverse_lazy('papers:paper-list')


class PaperListView(ListView):
    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            if user.is_staff:
                return Paper.objects.all()
            else:
                return Paper.objects.filter(
                    Q(created_by=user) |
                    Q(authors__id=user.author.id)
                ).distinct()
        else:
            return Paper.objects.none()


@login_required
def paper_create(request):
    AuthorFormSet = modelformset_factory(
        Author,
        form=AuthorForm,
        extra=1,
        can_delete=True
    )
    first_author = request.user.author
    paper_form_prefix = "paper_form"
    author_formset_prefix = "author_formset"

    if request.method == 'POST':
        paper_form = PaperForm(request.POST, request.FILES, prefix=paper_form_prefix)
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix=author_formset_prefix)

        if paper_form.is_valid() and author_formset.is_valid():
            paper = paper_form.save(commit=False)
            paper.created_by = request.user
            paper.filename = request.FILES[f'{paper_form_prefix}-file'].name
            paper.save()

            authors = author_formset.save()
            authors.insert(0, first_author)
            for author in authors:
                paper.authors.add(author)

            paper_form.save_m2m()

            return redirect('papers:paper-detail', pk=paper.pk)
    else:
        paper_form = PaperForm(prefix=paper_form_prefix)
        author_formset = AuthorFormSet(prefix=author_formset_prefix, queryset=Author.objects.none())
    return render(request, 'papers/paper_form.html', {
        'author_formset': author_formset,
        'paper_form': paper_form,
        'first_author': first_author,
    })


@permission_required('papers.access_paper', fn=objectgetter(Paper, 'pk'))
def paper_update(request, pk):
    AuthorFormSet = modelformset_factory(
        Author,
        form=AuthorForm,
        extra=1,
        can_delete=True
    )
    paper = get_object_or_404(Paper, pk=pk)
    first_author = paper.created_by.author
    paper_form_prefix = "paper_form"
    author_formset_prefix = "author_formset"

    if request.method == 'POST':
        paper_form = PaperForm(request.POST, request.FILES, prefix=paper_form_prefix, instance=paper)
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix=author_formset_prefix)

        if paper_form.is_valid() and author_formset.is_valid():
            old_filename = paper.filename
            paper = paper_form.save(commit=False)
            if 'file' in paper_form.changed_data:
                paper.filename = request.FILES[f'{paper_form_prefix}-file'].name
            else:
                paper.filename = old_filename

            paper.save()

            authors = author_formset.save()
            authors.insert(0, first_author)
            for author in authors:
                paper.authors.add(author)

            paper_form.save_m2m()

            return redirect('papers:paper-detail', pk=paper.pk)
    else:
        paper_form = PaperForm(prefix=paper_form_prefix, instance=paper)
        editable_authors = paper.authors.exclude(pk=first_author.id)
        author_formset = AuthorFormSet(prefix=author_formset_prefix,
                                       queryset=editable_authors)
    return render(request, 'papers/paper_form.html', {
        'author_formset': author_formset,
        'paper_form': paper_form,
        'first_author': first_author,
    })


@permission_required('papers.access_paper', fn=objectgetter(Paper, 'pk'))
def paper_download(request, pk):
    paper = get_object_or_404(Paper.objects.only('file', 'filename'), pk=pk)

    if settings.DEBUG:
        from django.views.static import serve
        filename = paper.file.name
        return serve(request, filename, settings.MEDIA_ROOT)

    original_filename = quote_plus(paper.filename)
    real_filename = quote_plus(paper.file.name)
    mimetype = magic.from_file(paper.file.path, mime=True)

    response = HttpResponse(content_type=mimetype)
    response['Content-Disposition'] = f'attachment; filename*=utf-8\'\'{original_filename}'
    response['X-Accel-Redirect'] = f'/protected/{real_filename}'
    return response


class AuthorDetailView(PermissionRequiredMixin, SimpleDetailView):
    model = Author
    permission_required = 'papers.access_author'
    fields = ['first_name',
              'last_name',
              'email_address',
              'affiliation',
              'postal_address',
              'phone_number',
              ]


class UserDetailView(PermissionRequiredMixin, SimpleDetailView):
    model = User
    permission_required = 'papers.access_user'
    queryset = User.objects.select_related('author')
    fields = {'user': ['email'],
              'author': ['first_name',
                         'last_name',
                         'email_address',
                         'affiliation',
                         'postal_address',
                         'phone_number',
                         ]}


def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        author_form = AuthorForm(request.POST)

        if user_form.is_valid() and author_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            author_form = AuthorForm(request.POST, instance=user.author)
            author_form.full_clean()
            author_form.save()

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('papers:paper-list')
    else:
        user_form = RegisterForm()
        author_form = AuthorForm()
    return render(request, 'registration/user_form.html', {
        'user_form': user_form,
        'author_form': author_form
    })


@permission_required('papers.access_user', fn=objectgetter(User, 'pk'))
def user_update(request, *args, **kwargs):
    user_id = kwargs.get('pk')
    user = User.objects.select_related('author').get(pk=user_id)
    author = user.author

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=user)
        author_form = AuthorForm(request.POST, instance=author)

        if user_form.is_valid() and author_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            author_form.save()
            return redirect('user-detail', pk=user_id)
    else:
        user_form = UserUpdateForm(instance=user)
        author_form = AuthorForm(instance=author)
    return render(request, 'registration/user_form.html', {
        'user_form': user_form,
        'author_form': author_form
    })

papers/templates/papers/author_detail.html
{% extends 'papers/base.html' %}

{% load i18n %}
{% load custom_tags %}

{% block header %}
    <h1>{% trans 'Author details' %}</h1>
{% endblock %}

{% block content %}
    <div>
        {% render_fields author fields %}
    </div>

    <a class="pure-button" href="{{ request.META.HTTP_REFERER }}">
        {% trans "Back" %}
    </a>
{% endblock %}

papers/templates/papers/base.html
{% load i18n %}
{% load static %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% trans 'Papers application' context "application's name" %}</title>
</head>

<body>
    <div class="main">
        <div class="header">
            {% block header %}
            {% endblock %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

papers/templates/papers/paper_confirm_delete.html
{% extends 'papers/base.html' %}

{% load i18n %}

{% block header %}
    <h1>{% trans 'Delete paper' %}</h1>
{% endblock %}

{% block content %}
    <form class="pure-form" method="post">
        {% csrf_token %}
        <p>
            {% blocktrans %}
                Are you sure you want to delete "{{ object }}"?
            {% endblocktrans %}
        </p>
        <input class="pure-button button-delete" type="submit" value="{% trans 'Confirm' %}">
        <a class="pure-button" href="{% url 'papers:paper-list' %}">
            {% trans 'Back' %}
        </a>
    </form>
{% endblock %}

papers/templates/papers/paper_detail.html
{% extends 'papers/base.html' %}

{% load i18n %}
{% load l10n %}
{% load custom_tags %}

{% block content %}
    <h1>{{ paper.title }}</h1>

    <div>
        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'created_at' }}:
            </span>
            {{ paper.created_at }}
        </p>

        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'modified_at' }}:
            </span>
            {{ paper.modified_at }}
        </p>

        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'abstract' }}:
            </span>
            {{ paper.abstract|linebreaksbr }}
        </p>

        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'authors' }}:
            </span>
        </p>
        <ul>
            {% for author in paper.authors.all %}
                <li>
                    <a href="{{ author.get_absolute_url }}">
                        {{ author }}
                    </a>
                </li>
            {% endfor %}
        </ul>

        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'keywords' }}:
            </span>
            {{ paper.keywords.all|join:", " }}
        </p>

        <p>
            <span class="field-label">
                {{ paper|get_field_verbose_name:'file' }}:
            </span>
            <a class="pure-button" href="{% url 'papers:paper-download' paper.id  %}">
                {% trans "Download" %}
            </a>
        </p>

        <p>
            <a class="pure-button pure-button-primary" href="{% url 'papers:paper-update' pk=paper.id %}">
                {% trans "Edit" %}
            </a>
            <a class="pure-button button-delete" href="{% url 'papers:paper-delete' pk=paper.id %}">
                {% trans "Delete" %}
            </a>
        </p>
    </div>

    <a class="pure-button" href="{% url 'papers:paper-list' %}">
        {% trans 'Back' %}
    </a>
{% endblock %}

papers/templates/papers/paper_form.html
{% extends 'papers/base.html' %}

{% load i18n %}
{% load static %}

{% block header %}
    <h1>
        {% if paper_form.instance.id %}
            {% trans 'Edit paper' %}
        {% else %}
            {% trans 'Create paper' %}
        {% endif %}
    </h1>
{% endblock %}

{% block content %}
    <form class="pure-form pure-form-aligned" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p class="form-error">{{ paper_form.non_field_errors }}</p>

        {% include 'includes/form_field.html' with field=paper_form.title %}
        {% include 'includes/form_field.html' with field=paper_form.abstract %}
        {% include 'includes/form_field.html' with field=paper_form.keywords %}

        {{ author_formset.management_form }}

        <div id="formset">
            <p class="pure-controls">
                {% blocktrans %}
                    {{ first_author }} will be the first author
                {% endblocktrans %}
            </p>

            <div class="pure-control-group">
                <label>{% trans 'Other authors' %}</label>
            </div>

            {% for form in author_formset.forms %}
                <div class="author-form">
                    <p class="form-error">{{ form.non_field_errors }}</p>
                    {% include 'includes/form.html' %}
                </div>
            {% endfor %}
        </div>

        {% include 'includes/form_field.html' with field=paper_form.file %}

        <div class="pure-controls">
            <button class="pure-button pure-button-primary" type="submit">
                {% trans 'Submit' %}
            </button>

            {% if paper_form.instance.id %}
                {% url 'papers:paper-detail' pk=paper_form.instance.id as back_url %}
            {% else %}
                {% url 'papers:paper-list' as back_url %}
            {% endif %}

            <a class="pure-button" href="{{ back_url }}">
                {% trans 'Back' %}
            </a>
        </div>
    </form>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>

    <script>
        $('.author-form').formset({
            'prefix': 'author_formset',
            'addText': '{% trans "Add author" %}',
            'deleteText': '{% trans "Delete author" %}',
            'addCssClass': 'pure-button button-add',
            'deleteCssClass': 'pure-button button-delete delete-author'
        });
    </script>
{% endblock %}

papers/templates/papers/paper_list.html
{% extends 'papers/base.html' %}

{% load i18n %}
{% load custom_tags %}

{% block header %}
    <h1>{% trans 'Papers application' %}</h1>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>{% trans 'My papers' %}</h2>

        {% if paper_list %}
            <table class="pure-table">
                <thead>
                    <tr>
                        {% with paper=paper_list|first %}
                            <th class="field-label">
                                {{ paper|get_field_verbose_name:'title'}}
                            </th>
                            <th class="field-label">
                                {% trans 'Edit' %}
                            </th>
                            <th class="field-label">
                                {{ paper|get_field_verbose_name:'file'}}
                            </th>
                        {% endwith %}
                    </tr>
                </thead>

                <tbody>
                    {% for paper in paper_list %}
                        <tr>
                            <td>
                                <a href="{% url 'papers:paper-detail' paper.id %}">
                                    {{ paper.title }}
                                </a>
                            </td>

                            <td>
                                <a class="pure-button" href="{% url 'papers:paper-update' paper.id %}">
                                    {% trans 'Edit' %}
                                </a>
                            </td>

                            <td>
                                <a class="pure-button" href="{% url 'papers:paper-download' paper.id  %}">
                                    {% trans 'Download' %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>{% trans 'No papers are available.' %}</p>
        {% endif %}

        <p>
            <a href="{% url 'papers:paper-create' %}" class="pure-button pure-button-primary">
                {% trans 'New paper' %}
            </a>
        </p>
        <p>
            {% url 'user-detail' user.id as user_url  %}
            {% blocktrans %}
                Logged in as <a href="{{ user_url }}">{{ user }}</a>
            {% endblocktrans %}
        </p>
        {% if user.is_staff %}
            <p>
                <a class="pure-button" href="{% url 'admin:index' %}">
                    {% trans 'Admin page' %}
                </a>
            </p>
        {% endif %}
        <p>
            <a class="pure-button" href="{% url 'logout' %}">
                {% trans 'Logout' %}
            </a>
        </p>
    {% else %}
        <p>
            <a class="pure-button pure-button-primary" href="{% url 'login' %}">
                {% trans 'Login' %}
            </a>
        </p>
        <p>
            <a class="pure-button" href="{% url 'register' %}">
                {% trans 'Register' %}
            </a>
        </p>
    {% endif %}
{% endblock %}